var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(h,w,m){h!=Array.prototype&&h!=Object.prototype&&(h[w]=m.value)};$jscomp.getGlobal=function(h){return"undefined"!=typeof window&&window===h?h:"undefined"!=typeof global&&null!=global?global:h};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(h,w,m,l){if(w){m=$jscomp.global;h=h.split(".");for(l=0;l<h.length-1;l++){var n=h[l];n in m||(m[n]={});m=m[n]}h=h[h.length-1];l=m[h];w=w(l);w!=l&&null!=w&&$jscomp.defineProperty(m,h,{configurable:!0,writable:!0,value:w})}};$jscomp.polyfill("Array.prototype.fill",function(h){return h?h:function(h,m,l){var n=this.length||0;0>m&&(m=Math.max(0,n+m));if(null==l||l>n)l=n;l=Number(l);0>l&&(l=Math.max(0,n+l));for(m=Number(m||0);m<l;m++)this[m]=h;return this}},"es6","es3");
$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.symbolCounter_=0;$jscomp.Symbol=function(h){return $jscomp.SYMBOL_PREFIX+(h||"")+$jscomp.symbolCounter_++};
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var h=$jscomp.global.Symbol.iterator;h||(h=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[h]&&$jscomp.defineProperty(Array.prototype,h,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(h){var w=0;return $jscomp.iteratorPrototype(function(){return w<h.length?{done:!1,value:h[w++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(h){$jscomp.initSymbolIterator();h={next:h};h[$jscomp.global.Symbol.iterator]=function(){return this};return h};$jscomp.iteratorFromArray=function(h,w){$jscomp.initSymbolIterator();h instanceof String&&(h+="");var m=0,l={next:function(){if(m<h.length){var n=m++;return{value:w(n,h[n]),done:!1}}l.next=function(){return{done:!0,value:void 0}};return l.next()}};l[Symbol.iterator]=function(){return l};return l};
$jscomp.polyfill("Array.prototype.keys",function(h){return h?h:function(){return $jscomp.iteratorFromArray(this,function(h){return h})}},"es6","es3");
$jscomp.polyfill("String.fromCodePoint",function(h){return h?h:function(h){for(var m="",l=0;l<arguments.length;l++){var n=Number(arguments[l]);if(0>n||1114111<n||n!==Math.floor(n))throw new RangeError("invalid_code_point "+n);65535>=n?m+=String.fromCharCode(n):(n-=65536,m+=String.fromCharCode(n>>>10&1023|55296),m+=String.fromCharCode(n&1023|56320))}return m}},"es6","es3");
(function(h,w){function m(a,b){a=Object.create(a);for(var c in b)a[c]=b[c];b.toString!==Object.prototype.toString&&(a.toString=b.toString);return a}function l(a,b){if(null==b)return null;null==b.__id__&&(b.__id__=w.$haxeUID++);var c;null==a.hx__closures__?a.hx__closures__={}:c=a.hx__closures__[b.__id__];null==c&&(c=b.bind(a),a.hx__closures__[b.__id__]=c);return c}var n=function(){return H.__string_rec(this,"")},R=R||{},p,I=function(){this.events=new O;this.onerror=this.onload=this.onprogress=this.ontimeout=
null};I.__name__=!0;I.prototype={addEventListener:function(a,b){var c=this.events.h[a];null==c&&(c=[],this.events.h[a]=c);c.push(b)},removeEventListener:function(a,b){a=this.events.h[a];null!=a&&t.remove(a,b)},dispatchEvent:function(a){null!=a.type&&0==a.type.indexOf("on")&&(a.type=t.substr(a.type,2,null));var b=this.events.h[a.type];if(null!=b)for(var c=0;c<b.length;){var d=b[c];++c;d(a)}},triggerEvent:function(a,b){null==b&&(b=new D(a));b.target=null!=b.target?b.target:this;"function"===typeof this["on"+
a]&&this["on"+a].call(this,b);this.dispatchEvent(b)}};var P=h.Element=function(){this.width=this.height=0;I.call(this);this.style=new Y};P.__name__=!0;P.__super__=I;P.prototype=m(I.prototype,{});var q=h.HTMLElement=function(a){P.call(this);this.tagName=a};q.__name__=!0;q.__super__=P;q.prototype=m(P.prototype,{getBoundingClientRect:function(){var a={x:0,y:0,top:0,left:0,width:g._window.innerWidth,height:g._window.innerHeight};a.right=this.width;a.bottom=this.height;return a},appendChild:function(a){}});
var Q=h.HTMLCanvasElement=function(a){q.call(this,a)};Q.__name__=!0;Q.__super__=q;Q.prototype=m(q.prototype,{toDataURL:function(){return"data:,"}});var E=h.Canvas=function(){Q.call(this,"CANVAS");this._wxCanvas=wx.createCanvas();E.CANVAS_COUNT++;window.wxdebug&&u.trace("CANVAS_COUNT=",{fileName:"src/Canvas.hx",lineNumber:43,className:"Canvas",methodName:"new",customParams:[E.CANVAS_COUNT]});k.definePropertySetGet(this,"width",l(this,this.set_width),l(this,this.get_width));k.definePropertySetGet(this,
"height",l(this,this.set_height),l(this,this.get_height));this.width=this._wxCanvas.width;this.height=this._wxCanvas.height};E.__name__=!0;E.__super__=Q;E.prototype=m(Q.prototype,{cleanup:function(){null!=this._wxCanvas&&(this._wxCanvas=null,E.CANVAS_COUNT--,window.wxdebug&&u.trace("CANVAS_COUNT=",{fileName:"src/Canvas.hx",lineNumber:64,className:"Canvas",methodName:"cleanup",customParams:[E.CANVAS_COUNT]}));null!=this._context2d&&(this._context2d.cleanup(),this._context2d=null);this._gl=null},getAttribute:function(a){return""},
setAttribute:function(a,b){},set_width:function(a){return null==this._wxCanvas?0:this.clientWidth=this._wxCanvas.width=a},get_width:function(){return null==this._wxCanvas?0:this._wxCanvas.width},set_height:function(a){return null==this._wxCanvas?0:this.clientHeight=this._wxCanvas.height=a},get_height:function(){return null==this._wxCanvas?0:this._wxCanvas.height},toTempFilePath:function(a){this._wxCanvas.toTempFilePath(a)},toTempFilePathSync:function(a){return this._wxCanvas.toTempFilePathSync(a)},
getContext:function(a){"2d"!=a&&(a="webgl");if("2d"==a)return null==this._context2d&&(this._context2d=new B(this._wxCanvas.getContext(a)),this._context2d._canvas=this._wxCanvas),this._context2d;null==this._gl&&(this._gl=this._wxCanvas.getContext(a,{antialias:!0,stencil:!0,vsync:!0}),this._gl.antialias=!0,this.varWebGLRenderingContext2D(this._gl));a=this._gl.getContextAttributes();u.trace("attributes=",{fileName:"src/Canvas.hx",lineNumber:156,className:"Canvas",methodName:"getContext",customParams:[a]});
try{u.trace("attributes2=",{fileName:"src/Canvas.hx",lineNumber:158,className:"Canvas",methodName:"getContext",customParams:[JSON.stringify(a)]})}catch(b){}return this._gl},putImageData:function(){},varWebGLRenderingContext2D:function(a){if(null!=a){var b=a.getExtension;a.getExtension=function(){return b.apply(this,arguments)};var c=a.texImage2D;a.texImage2D=function(){if(6==arguments.length){if(null==arguments[5]){console.log("\u65e0\u6cd5\u6e32\u67d3");return}if(null!=arguments[5]._wxCanvas)arguments[5]=
arguments[5]._wxCanvas;else if(null!=arguments[5]._contextImage)arguments[5]=arguments[5]._contextImage;else return}c.apply(this,arguments)};var d=a.getProgramParameter;a.getProgramParameter=function(){var b=d.apply(a,arguments);return null==b?-1:b}}},uniformFix:function(a,b){var c=G.getProperty(a,b);null!=c&&G.setProperty(a,b,function(){if(null==arguments[0])throw"uniformFix:"+b;c.apply(this,arguments)})}});(h.CanvasRenderingContext2D=function(){}).__name__=!0;var B=function(a){this._size=0;var b=
this;B.CONTEXT2D_COUNT++;window.contextCount=B.CONTEXT2D_COUNT;this._context=a;k.definePropertySetGet(this,"globalAlpha",function(a){b._context.globalAlpha=a},function(){return b._context.globalAlpha});k.definePropertySetGet(this,"canvas",function(a){b._canvas=a},function(){return b._canvas});k.definePropertySetGet(this,"textAlign",function(a){b._context.textAlign=a},function(){return"start"});k.definePropertySetGet(this,"font",function(a){var c=a.split(" ");a=t.substr(a,a.indexOf("'")+1,null);a=
t.substr(a,0,a.lastIndexOf("'"));for(var e=0;e<c.length;){var f=c[e];++e;if(-1!=f.indexOf("px")){b._size=C.parseInt(t.substr(f,0,f.lastIndexOf("px")));-1!=f.indexOf("/")&&(f=t.substr(f,f.indexOf("/")+1,null));a=r.replace(a,"/","");a=r.replace(a,".","");-1!=a.indexOf(" ")&&(a='"'+a+'"');-1!=a.indexOf("px")?b._context.font=a:b._context.font=f+" "+a;break}}},function(){return b._context.font});k.definePropertySetGet(this,"fillStyle",function(a){b._context.fillStyle=a},function(){return b._context.fillStyle});
k.definePropertySetGet(this,"textBaseline",function(a){b._context.textBaseline=a},function(){return b._context.textBaseline});k.definePropertySetGet(this,"imageSmoothingEnabled",function(a){b._context.imageSmoothingEnabled=a},function(){return b._context.imageSmoothingEnabled})};B.__name__=!0;B.prototype={get_canvas:function(){return this._canvas},createRadialGradient:function(a,b,c,d,e,f){return this._context.createRadialGradient.apply(this._context,arguments)},bezierCurveTo:function(a,b,c,d,e,f){this._context.bezierCurveTo.apply(this._context,
arguments)},cleanup:function(){null!=this._context&&(B.CONTEXT2D_COUNT--,window.contextCount=B.CONTEXT2D_COUNT);this._canvas=this._context=null},createLinearGradient:function(a,b,c,d){return this._context.createLinearGradient.apply(this._context,arguments)},translate:function(a,b){this._context.translate.apply(this._context,arguments)},clearRect:function(a,b,c,d){null!=this._context&&(null==a||null==b||null==c||null==d?this._context.clearRect(0,0,0,0):this._context.clearRect(a,b,c,d))},set_strokeStyle:function(a){this._context.strokeStyle=
a;return this._context.strokeStyle},get_strokeStyle:function(){return this._context.strokeStyle},createImageData:function(a,b){return this._context.createImageData.apply(this._context,arguments)},moveTo:function(a,b){this._context.moveTo.apply(this._context,arguments)},lineTo:function(a,b){this._context.lineTo.apply(this._context,arguments)},rect:function(a,b,c,d){this._context.rect.apply(this._context,arguments)},fillRect:function(a,b,c,d){this._context.fillRect.apply(this._context,arguments)},createPattern:function(a,
b){var c=null;null!=a._wxCanvas?c=a._wxCanvas:null!=a._contextImage&&(c=a._contextImage);return null==c?null:this._context.createPattern(c,b)},quadraticCurveTo:function(a,b,c,d){this._context.quadraticCurveTo.apply(this._context,arguments)},getImageData:function(a,b,c,d){return this._context.getImageData.apply(this._context,arguments)},putImageData:function(a,b,c){this._context.putImageData.apply(this._context,arguments)},setImageData:function(){},drawImage:function(a,b,c,d,e,f,g,h,k){null!=a._contextImage?
a=a._contextImage:null!=a._wxCanvas&&(a=a._wxCanvas);this._context.drawImage(a,b,c,d,e,f,g,h,k)},beginPath:function(){this._context.beginPath()},closePath:function(){this._context.closePath()},fill:function(){this._context.fill()},stroke:function(a){this._context.stroke.apply(this._context,arguments)},fillText:function(a,b,c){this._context.fillText(a,b,c)},measureText:function(a){for(var b=0,c=0,d=a.length;c<d;){var e=c++,f=a.charAt(e);e=this._size+"_"+f;Object.prototype.hasOwnProperty.call(B.__measureTextSizeMaps.h,
e)||(f=this._context.measureText(f),B.__measureTextSizeMaps.h[e]=null==f?0:f.width);b+=B.__measureTextSizeMaps.h[e]}return{width:b}},transform:function(a,b,c,d,e,f){this._context.transform.apply(this._context,arguments)},save:function(){this._context.save()},clip:function(){this._context.clip()},restore:function(){this._context.restore()},setTransform:function(a,b,c,d,e,f){null!=this._context&&null!=this._context.setTransform&&this._context.setTransform(a,b,c,d,e,f)},isPointInStroke:function(a,b,
c){return this._context.isPointInStroke.apply(this._context,arguments)},isPointInPath:function(a,b,c,d){return this._context.isPointInPath.apply(this._context,arguments)},arc:function(a,b,c,d,e,f){this._context.arc.apply(this._context,arguments)},arcTo:function(a,b,c,d,e){this._context.arcTo.apply(this._context,arguments)},__properties__:{set_strokeStyle:"set_strokeStyle",get_strokeStyle:"get_strokeStyle",get_canvas:"get_canvas"}};var Y=function(){};Y.__name__=!0;Y.prototype={setProperty:function(a,
b,c){}};var M=h.HTMLAudioElement=function(a){q.call(this,a)};M.__name__=!0;M.__super__=q;M.prototype=m(q.prototype,{});var V=h.HTMLDocument=function(a){this.readyState="complete";q.call(this,a)};V.__name__=!0;V.__super__=q;V.prototype=m(q.prototype,{exitFullscreen:function(){},getElementById:function(a){return"GameCanvas"==a||"webgl"==a||null!=window.canvas&&a==window.canvas.id?window.canvas:null},createElementNS:function(a){return null},createTextNode:function(a){return null},createElement:function(a){a=
a.toLowerCase();return"textcanvas"==a?(null==this.textcanvas&&(this.textcanvas=new E),this.textcanvas.getContext("2d").clearRect(0,0,this.textcanvas.width,this.textcanvas.height),this.textcanvas):"canvas"==a?new E:new q(a)}});var z=h.HTMLImageElement=function(){this.src=this._src=null;q.call(this,"IMG");window.wxdebug&&u.trace("create canvas IMAGE_COUNT=",{fileName:"src/HTMLImageElement.hx",lineNumber:28,className:"HTMLImageElement",methodName:"new",customParams:[z.IMAGE_COUNT]});k.definePropertySetGet(this,
"src",l(this,this.set_src),l(this,this.get_src));k.definePropertySetGet(this,"width",l(this,this.set_width),l(this,this.get_width));k.definePropertySetGet(this,"height",l(this,this.set_height),l(this,this.get_height))};z.__name__=!0;z.__super__=q;z.prototype=m(q.prototype,{createImage:function(){var a=this;null==this._contextImage&&(z.IMAGE_COUNT++,window.imageCount=z.IMAGE_COUNT,this._contextImage=wx.createImage(),this._contextImage.onload=function(){a.width=a._contextImage.width;a.height=a._contextImage.height;
a.triggerEvent("load")},this._contextImage.onerror=function(b){a.triggerEvent("error")})},disposeImage:function(){null!=this._contextImage&&(z.IMAGE_COUNT--,window.imageCount=z.IMAGE_COUNT,window.wxdebug&&u.trace("delete canvas IMAGE_COUNT=",{fileName:"src/HTMLImageElement.hx",lineNumber:67,className:"HTMLImageElement",methodName:"disposeImage",customParams:[z.IMAGE_COUNT,this._contextImage.src]}),this._contextImage.onload=null,this._contextImage.onerror=null,this._contextImage.src="",this._contextImage=
null)},set_width:function(a){return this._width=a},get_width:function(){return this._width},set_height:function(a){return this._height=a},get_height:function(){return this._height},set_src:function(a){var b=this;k.ofPathNoSync(a,function(a){0==a.indexOf("data:")||-1!=a.indexOf(k.START)||-1!=a.indexOf("photo://")?(b._src=a,-1==a.indexOf("photo://")?b._src=r.replace(b._src,k.START,""):b._src=r.replace(b._src,"photo://",k.START),b.createImage(),b._contextImage.src=b._src):k.cacheAssets(a,"binary",function(a){b.createImage();
b._src=a;b._contextImage.src=a},function(){b.createImage();b._src=a;b._contextImage.src=a},!0)||(b._src=a,b.createImage(),b._contextImage.src=a)});return this._src},get_src:function(){return this._src}});var O=function(){this.h=Object.create(null)};O.__name__=!0;O.prototype={exists:function(a){return Object.prototype.hasOwnProperty.call(this.h,a)},set:function(a,b){this.h[a]=b},remove:function(a){return Object.prototype.hasOwnProperty.call(this.h,a)?(delete this.h[a],!0):!1}};var k=function(){};k.__name__=
!0;k.isArrayBuffer=function(a){return a instanceof ArrayBuffer};k.definePropertySetGet=function(a,b,c,d){Object.defineProperty(a,b,{enumerable:!0,configurable:!0,set:c,get:d})};k.isString=function(a){return"string"===typeof a};k.ofPathNoSync=function(a,b){b(k.ofPath(a))};k.ofPath=function(a){0==a.indexOf("data:image")||0==a.indexOf("http")&&!k.isLocalAssets(a)||-1!=a.indexOf(k.START)||-1!=a.indexOf("photo://")||(null==window.webPath||k.isLocalAssets(a)?(0==a.indexOf(window.webPath+"/")&&(a=r.replace(a,
window.webPath+"/","")),-1==a.indexOf(k.START)&&(a=J.join([k.START,a])),-1!=a.indexOf("?")&&(a=t.substr(a,0,a.lastIndexOf("?")))):a=J.join([window.webPath,a]));return a};k.isLocalAssetsNoSync=function(a,b){0==a.indexOf(window.webPath+"/")&&(a=r.replace(a,window.webPath+"/",""));0==a.indexOf("http")&&b(!1);-1!=a.indexOf("?")&&(a=t.substr(a,0,a.lastIndexOf("?")));wx.getFileSystemManager().access({path:a,success:function(a){b(!0)},fail:function(a){b(!1)}})};k.isLocalAssets=function(a){0==a.indexOf(window.webPath+
"/")&&(a=r.replace(a,window.webPath+"/",""));if(0==a.indexOf("http"))return!1;-1!=a.indexOf("?")&&(a=t.substr(a,0,a.lastIndexOf("?")));try{return wx.getFileSystemManager().accessSync(a),!0}catch(b){return!1}};k.ofLocalPath=function(a){return wx.env.USER_DATA_PATH+"/"+N.encode(a)};k.cacheAssets=function(a,b,c,d,e){null==e&&(e=!1);if(0==a.indexOf(k.START)){a=r.replace(a,k.START,"");if(e)return c(a),!0;var f={filePath:a,success:function(a){c(a)},fail:function(){d()}};"binary"==b?b=null:f.encoding=b;
wx.getFileSystemManager().readFile(f);return!0}if(Object.prototype.hasOwnProperty.call(k.tempFileMaps.h,a))return e?c(k.tempFileMaps.h[a]):("binary"==b&&(b=null),f=k.tempFileMaps.h[a],wx.getFileSystemManager().readFile({filePath:f,encoding:b,success:function(a){c(a)},fail:function(a){u.trace("\u4e34\u65f6\u6587\u4ef6\u8bfb\u53d6\u5931\u8d25\uff1a",{fileName:"src/HTMLUtils.hx",lineNumber:230,className:"HTMLUtils",methodName:"cacheAssets",customParams:[a]});d()}})),!0;if(0!=a.indexOf("http"))return!1;
f=!1;for(var g=0,h=k.cacheExt;g<h.length;){var l=h[g];++g;if(-1!=a.indexOf(l)){f=!0;break}}if(!f)return!1;k.downloadTempFile(a,function(f){e?c(f):("binary"==b&&(b=null),f=k.tempFileMaps.h[a],wx.getFileSystemManager().readFile({filePath:f,encoding:b,success:function(a){c(a)},fail:function(a){u.trace("\u4e34\u65f6\u6587\u4ef6\u8bfb\u53d6\u5931\u8d25-2\uff1a",{fileName:"src/HTMLUtils.hx",lineNumber:265,className:"HTMLUtils",methodName:"cacheAssets",customParams:[a]});d()}}))},d);return!0};k.arrayBufferToString=
function(a){if(k.isArrayBuffer(a)){var b="",c=0,d=new Uint8Array(a);for(3<=d.length&&239===d[0]&&187===d[1]&&191===d[2]&&(c=3);c<d.length;)if(a=d[c],128>a)b+=String.fromCharCode(a),c++;else if(191<a&&224>a){if(c+1>=d.length)throw"UTF-8 Decode failed. Two byte character was truncated.";var e=d[c+1];b+=String.fromCharCode((a&31)<<6|e&63);c+=2}else{if(c+2>=d.length)throw"UTF-8 Decode failed. Multi byte character was truncated.";e=d[c+1];var f=d[c+2];b+=String.fromCharCode((a&15)<<12|(e&63)<<6|f&63);
c+=3}return b}return a};k.downloadTempFile=function(a,b,c){wx.downloadFile({url:a,timeout:6E4,enableHttp2:!0,success:function(d){var e=d.tempFilePath;null==e||""==e?k.downloadTempFile(a,b,c):(k.tempFileMaps.h[a]=e,b(d.tempFilePath))},fail:function(b){u.trace("wx.donwloadFile fail:",{fileName:"src/HTMLUtils.hx",lineNumber:347,className:"HTMLUtils",methodName:"downloadTempFile",customParams:[a,b]});c()}})};var t=function(){};t.__name__=!0;t.cca=function(a,b){a=a.charCodeAt(b);if(a==a)return a};t.substr=
function(a,b,c){if(null==c)c=a.length;else if(0>c)if(0==b)c=a.length+c;else return"";return a.substr(b,c)};t.remove=function(a,b){b=a.indexOf(b);if(-1==b)return!1;a.splice(b,1);return!0};t.now=function(){return Date.now()};M=h.Image=function(){z.call(this)};M.__name__=!0;M.__super__=z;M.prototype=m(z.prototype,{});var Z=function(){};Z.__name__=!0;Z.prototype={key:function(a){return wx.getStorageInfoSync().keys[a]},getItem:function(a){if(""==a)return null;a=wx.getStorageSync(a);return""==a?null:a},
setItem:function(a,b){wx.setStorage({key:a,data:b});return b},removeItem:function(a){},clear:function(){wx.clearStorageSync()}};var da=function(){this.protocol=""};da.__name__=!0;Math.__name__=!0;var ea=function(){this.appVersion="wechat";this.userAgent="zygame-dom"};ea.__name__=!0;var aa=function(){};aa.__name__=!0;aa.prototype={now:function(){return"devtools"==g.platform?wx.getPerformance().now():wx.getPerformance().now()/1E3|0}};var G=function(){};G.__name__=!0;G.getProperty=function(a,b){var c;
if(null==a)return null;var d=a.__properties__?c=a.__properties__["get_"+b]:!1;return d?a[c]():a[b]};G.setProperty=function(a,b,c){var d;var e=a.__properties__?d=a.__properties__["set_"+b]:!1;if(e)a[d](c);else a[b]=c};G.fields=function(a){var b=[];if(null!=a){var c=Object.prototype.hasOwnProperty,d;for(d in a)"__id__"!=d&&"hx__closures__"!=d&&c.call(a,d)&&b.push(d)}return b};var C=function(){};C.__name__=!0;C.string=function(a){return H.__string_rec(a,"")};C.parseInt=function(a){a=parseInt(a);return isNaN(a)?
null:a};var ba=function(){};ba.__name__=!0;ba.fromCharCode=function(a){return String.fromCodePoint(a)};var fa=function(){this.b=""};fa.__name__=!0;var r=function(){};r.__name__=!0;r.isSpace=function(a,b){a=t.cca(a,b);return 8<a&&14>a?!0:32==a};r.ltrim=function(a){for(var b=a.length,c=0;c<b&&r.isSpace(a,c);)++c;return 0<c?t.substr(a,c,b-c):a};r.rtrim=function(a){for(var b=a.length,c=0;c<b&&r.isSpace(a,b-c-1);)++c;return 0<c?t.substr(a,0,b-c):a};r.trim=function(a){return r.ltrim(r.rtrim(a))};r.replace=
function(a,b,c){return a.split(b).join(c)};var W=function(){q.call(this,"UPLOAD")};W.__name__=!0;W.__super__=q;W.prototype=m(q.prototype,{});var x=h.WebSocket=function(a,b){this.readyState=3;this.onclose=this.onerror=this.onmessage=this.onopen=null;this.extensions="";this.bufferedAmount=0;this.binaryType="";var c=this;if("string"!=typeof a||null==a||0!=a.indexOf("ws"))throw v.thrown("\u65e0\u6548\u7684 Scoket URL");window.unwss||-1==a.indexOf("ws://")||-1!=a.indexOf("127")||-1!=a.indexOf("192")||
(a=r.replace(a,"ws://","wss://"));this._baseSocket=wx.connectSocket({url:a,perMessageDeflate:!1});this._baseSocket.onClose(function(a){u.trace(a,{fileName:"src/WebSocket.hx",lineNumber:45,className:"WebSocket",methodName:"new"});if(c.readyState!=x.CLOSED&&(c.readyState=x.CLOSED,null!=c.onclose))c.onclose(a)});this._baseSocket.onMessage(function(a){if(c.readyState!=x.CLOSED&&null!=c.onmessage)c.onmessage(a)});this._baseSocket.onOpen(function(){if(c.readyState!=x.CLOSED&&(c.readyState=x.OPEN,null!=
c.onopen))c.onopen()});this._baseSocket.onError(function(a){u.trace(a,{fileName:"src/WebSocket.hx",lineNumber:70,className:"WebSocket",methodName:"new"});if(c.readyState!=x.CLOSED&&null!=c.onerror)c.onerror(a)});this.readyState=x.CONNECTING};x.__name__=!0;x.prototype={close:function(a,b){this.readyState=x.CLOSING;this._baseSocket.close({code:1E3,reason:b})},send:function(a){this._baseSocket.send({data:a})}};var u=function(){};u.__name__=!0;u.formatOutput=function(a,b){var c=C.string(a);if(null==b)return c;
var d=b.fileName+":"+b.lineNumber;if(null!=b.customParams){var e=0;for(b=b.customParams;e<b.length;)a=b[e],++e,c+=", "+C.string(a)}return d+": "+c};u.trace=function(a,b){a=u.formatOutput(a,b);"undefined"!=typeof console&&null!=console.log&&console.log(a)};var H=function(){};H.__name__=!0;H.__string_rec=function(a,b){if(null==a)return"null";if(5<=b.length)return"<...>";var c=typeof a;"function"==c&&(a.__name__||a.__ename__)&&(c="object");switch(c){case "function":return"<function>";case "object":if(a.__enum__){var d=
R[a.__enum__].__constructs__[a._hx_index];c=d._hx_name;if(d.__params__){b+="\t";var e=[],f=0;for(d=d.__params__;f<d.length;){var g=d[f];f+=1;e.push(H.__string_rec(a[g],b))}return c+"("+e.join(",")+")"}return c}if(a instanceof Array){c="[";b+="\t";e=0;for(f=a.length;e<f;)d=e++,c+=(0<d?",":"")+H.__string_rec(a[d],b);return c+"]"}try{e=a.toString}catch(ia){return"???"}if(null!=e&&e!=Object.toString&&"function"==typeof e&&(c=a.toString(),"[object Object]"!=c))return c;c="{\n";b+="\t";e=null!=a.hasOwnProperty;
f=null;for(f in a)e&&!a.hasOwnProperty(f)||"prototype"==f||"__class__"==f||"__super__"==f||"__interfaces__"==f||"__properties__"==f||(2!=c.length&&(c+=", \n"),c+=b+f+" : "+H.__string_rec(a[f],b));b=b.substring(1);return c+("\n"+b+"}");case "string":return a;default:return String(a)}};var g=h.Window=function(){this.supported=!0;this.devicePixelRatio=1;this.document=new V("DOM");q.call(this,"WINDOW");this.innerWidth=g.systemInfo.screenWidth;this.innerHeight=g.systemInfo.screenHeight;this.devicePixelRatio=
Math.max(this.innerWidth>this.innerHeight?1980/this.innerHeight:1080/this.innerWidth,this.innerHeight>this.innerWidth?1980/this.innerHeight:1080/this.innerHeight);var a=wx.getStorageSync("wechat_devicePixelRatio");if(""!=a||null!=a)a=C.parseInt(C.string(a)),1<=a&&a<this.devicePixelRatio&&(this.devicePixelRatio=a);"windows"==g.platform?this.devicePixelRatio=2:null!=g.systemInfo&&null!=g.systemInfo.pixelRatio?this.devicePixelRatio=g.systemInfo.pixelRatio:2<this.devicePixelRatio&&(this.devicePixelRatio=
2);console.log("\u5206\u8fa8\u7387\u6bd4\uff1a",this.devicePixelRatio,g.systemInfo.platform);window.devicePixelRatio=this.devicePixelRatio;this.location=new da;this.navigator=new ea;this.localStorage=new Z;this.document.location=this.location;wx.setPreferredFramesPerSecond(60);if(null!=wx.onAccelerometerChange)wx.onAccelerometerChange(l(this,this.onAccelerometerChange));if(null!=wx.onAudioInterruptionBegin)wx.onAudioInterruptionBegin(l(this,this.onHide));wx.onHide(l(this,this.onHide));if(null!=wx.onAudioInterruptionEnd)wx.onAudioInterruptionEnd(l(this,
this.onShow));wx.onShow(l(this,this.onShow));null!=wx.setKeepScreenOn&&wx.setKeepScreenOn({keepScreenOn:!0});try{wx.onMemoryWarning(function(){null!=wx.triggerGC&&wx.triggerGC()})}catch(b){console.log("wx.onMemoryWarning is not support!")}window.shareApp=g.share};g.__name__=!0;g.main=function(){g.canvas.id="mainCanvas";g.systemInfo=wx.getSystemInfoSync();g.platform=g.systemInfo.platform;g._window=new g;try{if(GameGlobal.isIOSHighPerformanceMode||"devtools"==g.platform||"windows"==g.platform||"mac"==
g.platform){for(var a in g._window){var b=Object.getOwnPropertyDescriptor(global,a);b&&!0!==b.configurable||"document"!=a&&"location"!=a&&Object.defineProperty(window,a,{value:g._window[a]})}null==window.document&&(window.document={});for(var c in g._window.document){var d=Object.getOwnPropertyDescriptor(window.document,c);d&&!0!==d.configurable||Object.defineProperty(window.document,c,{value:g._window.document[c]})}null==window.location&&Object.defineProperty(window,"location",{value:g._window.location});
window.parent=window}else{for(var e in g._window)global[e]=g._window[e];global.window=global;global.top=global.parent=global}}catch(f){a=v.caught(f),u.trace("Window.Exception",{fileName:"src/Window.hx",lineNumber:117,className:"Window",methodName:"main",customParams:[a.get_message(),ca.toString(a.get_stack())]})}null==window.performance&&(g._window.performance=new aa,window.performance=g._window.performance);window.platform=g.platform;window.systemInfo=g.systemInfo;window.showQuery={};g.listenerTouchEvent()};
g.listenerKeyEvent=function(){wx.onKeyDown(g.onKeyDown);wx.onKeyUp(g.onKeyUp)};g.onKeyDown=function(a){var b=new S("keydown");b.key=a.key;b.code=a.code;b.keyCode=a.key.charCodeAt(0);g._window.dispatchEvent(b)};g.onKeyUp=function(a){var b=new S("keyup");b.key=a.key;b.code=a.code;b.keyCode=a.key.charCodeAt(0);g._window.dispatchEvent(b)};g.listenerTouchEvent=function(){wx.onTouchStart(g.eventHandlerFactory("touchstart"));wx.onTouchMove(g.eventHandlerFactory("touchmove"));wx.onTouchEnd(g.eventHandlerFactory("touchend"));
wx.onTouchCancel(g.eventHandlerFactory("touchcancel"))};g.eventHandlerFactory=function(a){return function(b){"touchstart"==a?g.startTouch.push(b):"touchend"==a&&0<g.startTouch.length&&g.startTouch.shift();var c=new T(a);c.changedTouches=b.changedTouches;c.touches=b.touches;g.canvas.dispatchEvent(c)}};g.clearTouchStart=function(){for(var a=0,b=g.startTouch;a<b.length;){var c=b[a];++a;var d=new T("touchend");d.changedTouches=c.changedTouches;d.touches=c.touches;g.canvas.dispatchEvent(d)}};g.share=function(a,
b,c,d,e,f){null==e&&(e=!0);-1==b.indexOf("http")&&e&&(b=window.webPath+"/"+b);g.shareCallBack=c;c="";if("string"!=typeof d){e=G.fields(d);for(f=0;f<e.length;){var h=e[f];++f;c+=h+"="+C.string(G.getProperty(d,h))+"&"}c+="end=1"}else c=d;u.trace("share:",{fileName:"src/Window.hx",lineNumber:392,className:"Window",methodName:"share",customParams:[c]});wx.shareAppMessage({title:a,imageUrl:b,query:c});window.addEventListener("focus",g.onShareFocus)};g.onShareFocus=function(a){window.removeEventListener("focus",
g.onShareFocus);null!=g.shareCallBack&&g.shareCallBack()};g.__super__=q;g.prototype=m(q.prototype,{matchMedia:function(){return{addListener:function(a){}}},openAccelerometerChange:function(){wx.startAccelerometer({success:function(){},fail:function(){}})},closeAccelerometerChange:function(){wx.stopAccelerometer({success:function(){},fail:function(){}})},onAccelerometerChange:function(a){var b=new X;b.interval=20;b.accelerationIncludingGravity=a;g._window.triggerEvent("devicemotion",b)},onShow:function(a){u.trace("update ShowQuery=",
{fileName:"src/Window.hx",lineNumber:447,className:"Window",methodName:"onShow",customParams:[a]});window.showQuery=a;g._window.triggerEvent("focus");null!=wx.setKeepScreenOn&&wx.setKeepScreenOn({keepScreenOn:!0})},onHide:function(){g._window.triggerEvent("blur");g.clearTouchStart()}});var y=h.XMLHttpRequest=function(){this.responseType="text";this._requestHeader=new O;this.readyState=0;this.onabort=this.onloadstart=this.onloadend=this.onreadystatechange=null;I.call(this);this.upload=new W;this._requestHeader.h["content-type"]=
"application/x-www-from-urlencoded"};y.__name__=!0;y.__super__=I;y.prototype=m(I.prototype,{open:function(a,b,c,d,e){this.method=a;this.url=b;this.changeReadyState(y.OPENED)},overrideMimeType:function(a){},setRequestHeader:function(a,b){this._requestHeader.h[a]=b},send:function(a){var b=this;k.ofPathNoSync(this.url,function(c){b.url=c;var d=!1;-1!=b.url.indexOf("__zygameui.bitmap.path__")&&(b.url=r.replace(b.url,"__zygameui.bitmap.path__",""),d=!0);k.cacheAssets(b.url,"arraybuffer"==b.responseType?
"binary":"utf8",function(a){if(d)b.onSuccess({statusCode:200,data:a});else a.statusCode=200,b.onSuccess(a)},function(){b.onFail()},d)||b.sendRequest(a)})},sendRequest:function(a){for(var b=this,c={},d=Object.keys(this._requestHeader.h),e=d.length,f=0;f<e;){var g=d[f++];G.setProperty(c,g,this._requestHeader.h[g])}null!=a&&"string"!=typeof a&&(a=k.arrayBufferToString(a));c={url:this.url,method:this.method,header:c,timeout:6E3,responseType:this.responseType,success:l(this,this.onSuccess),fail:function(a){u.trace("wechat fail:",
{fileName:"src/XMLHttpRequest.hx",lineNumber:133,className:"XMLHttpRequest",methodName:"sendRequest",customParams:[b.url,a]});b.onFail()},dataType:"unjson"};null!=a&&(c.data=a);wx.request(c);this.triggerEvent("loadstart");this.changeReadyState(y.HEADERS_RECEIVED);this.changeReadyState(y.LOADING)},onSuccess:function(a){this.status=a.statusCode;k.isArrayBuffer(a.data)?"text"==this.responseType?this.responseText=this.response=k.arrayBufferToString(a.data):(this.response=a.data,this.responseText=null):
k.isString(a.data)?this.responseText=this.response=a.data:this.responseText=this.response=JSON.stringify(a.data);this.changeReadyState(y.DONE);this.triggerEvent("load");this.triggerEvent("loadend")},onFail:function(){this.changeReadyState(y.DONE);this.triggerEvent("error")},changeReadyState:function(a,b){this.readyState!=y.DONE&&(this.readyState=a,null==b&&(b={}),b.readyState=this.readyState,this.triggerEvent("readystatechange",b))},getAllResponseHeaders:function(){for(var a=[],b=Object.keys(this._requestHeader.h),
c=b.length,d=0;d<c;){var e=b[d++];a.push(e+":"+this._requestHeader.h[e])}return a.join("\n")}});var F=R["haxe.StackItem"]={__ename__:!0,__constructs__:null,CFunction:{_hx_name:"CFunction",_hx_index:0,__enum__:"haxe.StackItem",toString:n},Module:(p=function(a){return{_hx_index:1,m:a,__enum__:"haxe.StackItem",toString:n}},p._hx_name="Module",p.__params__=["m"],p),FilePos:(p=function(a,b,c,d){return{_hx_index:2,s:a,file:b,line:c,column:d,__enum__:"haxe.StackItem",toString:n}},p._hx_name="FilePos",p.__params__=
["s","file","line","column"],p),Method:(p=function(a,b){return{_hx_index:3,classname:a,method:b,__enum__:"haxe.StackItem",toString:n}},p._hx_name="Method",p.__params__=["classname","method"],p),LocalFunction:(p=function(a){return{_hx_index:4,v:a,__enum__:"haxe.StackItem",toString:n}},p._hx_name="LocalFunction",p.__params__=["v"],p)};F.__constructs__=[F.CFunction,F.Module,F.FilePos,F.Method,F.LocalFunction];var ca={toString:function(a){for(var b=new fa,c=0;c<a.length;){var d=a[c];++c;b.b+="\nCalled from ";
ca.itemToString(b,d)}return b.b},itemToString:function(a,b){switch(b._hx_index){case 0:a.b+="a C function";break;case 1:b=b.m;a.b+="module ";a.b+=null==b?"null":""+b;break;case 2:var c=b.s,d=b.file,e=b.line;b=b.column;null!=c&&(ca.itemToString(a,c),a.b+=" (");a.b+=null==d?"null":""+d;a.b+=" line ";a.b+=null==e?"null":""+e;null!=b&&(a.b+=" column ",a.b+=null==b?"null":""+b);null!=c&&(a.b+=")");break;case 3:c=b.classname;b=b.method;a.b+=C.string(null==c?"<unknown>":c);a.b+=".";a.b+=null==b?"null":""+
b;break;case 4:b=b.v,a.b+="local function #",a.b+=null==b?"null":""+b}}},v=function(a,b,c){Error.call(this,a);this.message=a;this.__previousException=b;this.__nativeException=null!=c?c:this;this.__skipStack=0;a=Error.prepareStackTrace;Error.prepareStackTrace=function(a){return a.stack};if(!(c instanceof Error))if(c=null,Error.captureStackTrace)Error.captureStackTrace(this,v),c=this;else if(c=Error(),"undefined"==typeof c.stack){try{throw c;}catch(d){}this.__skipStack++}this.stack=c.stack;Error.prepareStackTrace=
a};v.__name__=!0;v.caught=function(a){return a instanceof v?a:a instanceof Error?new v(a.message,null,a):new U(a,null,a)};v.thrown=function(a){if(a instanceof v)return a.get_native();if(a instanceof Error)return a;a=new U(a);a.__skipStack++;return a};v.__super__=Error;v.prototype=m(Error.prototype,{__shiftStack:function(){this.__skipStack++},get_message:function(){return this.message},get_native:function(){return this.__nativeException},get_stack:function(){var a=this.__exceptionStack;null==a&&(a=
K.toHaxe(K.normalize(this.stack),this.__skipStack),this.setProperty("__exceptionStack",a));return a},setProperty:function(a,b){try{Object.defineProperty(this,a,{value:b})}catch(c){this[a]=b}},__properties__:{get_native:"get_native",get_stack:"get_stack",get_message:"get_message"}});var ha=function(a,b){this.high=a;this.low=b};ha.__name__=!0;var K=function(){};K.__name__=!0;K.toHaxe=function(a,b){null==b&&(b=0);if(null==a)return[];if("string"==typeof a){a=a.split("\n");"Error"==a[0]&&a.shift();for(var c=
[],d=0,e=a.length;d<e;){var f=d++;if(!(b>f)){var g=a[f];f=g.match(/^    at ([$A-Za-z0-9_. ]+) \(([^)]+):([0-9]+):([0-9]+)\)$/);if(null!=f){g=f[1].split(".");"$hxClasses"==g[0]&&g.shift();var h=g.pop(),k=f[2],l=C.parseInt(f[3]);f=C.parseInt(f[4]);c.push(F.FilePos("Anonymous function"==h?F.LocalFunction():"Global code"==h?null:F.Method(g.join("."),h),k,l,f))}else c.push(F.Module(r.trim(g)))}}return c}return 0<b&&Array.isArray(a)?a.slice(b):a};K.normalize=function(a,b){null==b&&(b=0);if(Array.isArray(a)&&
0<b)return a.slice(b);if("string"==typeof a){switch(a.substring(0,6)){case "Error\n":case "Error:":++b}return K.skipLines(a,b)}return a};K.skipLines=function(a,b,c){null==c&&(c=0);return 0<b?(c=a.indexOf("\n",c),0>c?"":K.skipLines(a,--b,c+1)):a.substring(c)};var U=function(a,b,c){v.call(this,String(a),b,c);this.value=a;this.__skipStack++};U.__name__=!0;U.__super__=v;U.prototype=m(v.prototype,{});var N=function(){};N.__name__=!0;N.encode=function(a){var b=new N;a=b.doEncode(N.str2blks(a));return b.hex(a)};
N.str2blks=function(a){var b=A.ofString(a),c=(b.length+8>>6)+1;a=[];for(var d=0,e=16*c;d<e;){var f=d++;a[f]=0}f=0;e=b.length;for(d=8*e;f<e;)a[f>>2]|=b.b[f]<<(d+f)%4*8,++f;a[f>>2]|=128<<(d+f)%4*8;f=16*c-2;a[f]=d&255;a[f]|=(d>>>8&255)<<8;a[f]|=(d>>>16&255)<<16;a[f]|=(d>>>24&255)<<24;return a};N.prototype={bitOR:function(a,b){return(a>>>1|b>>>1)<<1|a&1|b&1},bitXOR:function(a,b){return(a>>>1^b>>>1)<<1|a&1^b&1},bitAND:function(a,b){return(a>>>1&b>>>1)<<1|a&1&b&1},addme:function(a,b){var c=(a&65535)+(b&
65535);return(a>>16)+(b>>16)+(c>>16)<<16|c&65535},hex:function(a){for(var b="",c=0;c<a.length;){var d=a[c];++c;b+="0123456789abcdef".charAt(d>>4&15)+"0123456789abcdef".charAt(d&15);b+="0123456789abcdef".charAt(d>>12&15)+"0123456789abcdef".charAt(d>>8&15);b+="0123456789abcdef".charAt(d>>20&15)+"0123456789abcdef".charAt(d>>16&15);b+="0123456789abcdef".charAt(d>>28&15)+"0123456789abcdef".charAt(d>>24&15)}return b},rol:function(a,b){return a<<b|a>>>32-b},cmn:function(a,b,c,d,e,f){return this.addme(this.rol(this.addme(this.addme(b,
a),this.addme(d,f)),e),c)},ff:function(a,b,c,d,e,f,g){return this.cmn(this.bitOR(this.bitAND(b,c),this.bitAND(~b,d)),a,b,e,f,g)},gg:function(a,b,c,d,e,f,g){return this.cmn(this.bitOR(this.bitAND(b,d),this.bitAND(c,~d)),a,b,e,f,g)},hh:function(a,b,c,d,e,f,g){return this.cmn(this.bitXOR(this.bitXOR(b,c),d),a,b,e,f,g)},ii:function(a,b,c,d,e,f,g){return this.cmn(this.bitXOR(c,this.bitOR(b,~d)),a,b,e,f,g)},doEncode:function(a){for(var b=1732584193,c=-271733879,d=-1732584194,e=271733878,f=0;f<a.length;){var g=
b,h=c,k=d,l=e;b=this.ff(b,c,d,e,a[f],7,-680876936);e=this.ff(e,b,c,d,a[f+1],12,-389564586);d=this.ff(d,e,b,c,a[f+2],17,606105819);c=this.ff(c,d,e,b,a[f+3],22,-1044525330);b=this.ff(b,c,d,e,a[f+4],7,-176418897);e=this.ff(e,b,c,d,a[f+5],12,1200080426);d=this.ff(d,e,b,c,a[f+6],17,-1473231341);c=this.ff(c,d,e,b,a[f+7],22,-45705983);b=this.ff(b,c,d,e,a[f+8],7,1770035416);e=this.ff(e,b,c,d,a[f+9],12,-1958414417);d=this.ff(d,e,b,c,a[f+10],17,-42063);c=this.ff(c,d,e,b,a[f+11],22,-1990404162);b=this.ff(b,
c,d,e,a[f+12],7,1804603682);e=this.ff(e,b,c,d,a[f+13],12,-40341101);d=this.ff(d,e,b,c,a[f+14],17,-1502002290);c=this.ff(c,d,e,b,a[f+15],22,1236535329);b=this.gg(b,c,d,e,a[f+1],5,-165796510);e=this.gg(e,b,c,d,a[f+6],9,-1069501632);d=this.gg(d,e,b,c,a[f+11],14,643717713);c=this.gg(c,d,e,b,a[f],20,-373897302);b=this.gg(b,c,d,e,a[f+5],5,-701558691);e=this.gg(e,b,c,d,a[f+10],9,38016083);d=this.gg(d,e,b,c,a[f+15],14,-660478335);c=this.gg(c,d,e,b,a[f+4],20,-405537848);b=this.gg(b,c,d,e,a[f+9],5,568446438);
e=this.gg(e,b,c,d,a[f+14],9,-1019803690);d=this.gg(d,e,b,c,a[f+3],14,-187363961);c=this.gg(c,d,e,b,a[f+8],20,1163531501);b=this.gg(b,c,d,e,a[f+13],5,-1444681467);e=this.gg(e,b,c,d,a[f+2],9,-51403784);d=this.gg(d,e,b,c,a[f+7],14,1735328473);c=this.gg(c,d,e,b,a[f+12],20,-1926607734);b=this.hh(b,c,d,e,a[f+5],4,-378558);e=this.hh(e,b,c,d,a[f+8],11,-2022574463);d=this.hh(d,e,b,c,a[f+11],16,1839030562);c=this.hh(c,d,e,b,a[f+14],23,-35309556);b=this.hh(b,c,d,e,a[f+1],4,-1530992060);e=this.hh(e,b,c,d,a[f+
4],11,1272893353);d=this.hh(d,e,b,c,a[f+7],16,-155497632);c=this.hh(c,d,e,b,a[f+10],23,-1094730640);b=this.hh(b,c,d,e,a[f+13],4,681279174);e=this.hh(e,b,c,d,a[f],11,-358537222);d=this.hh(d,e,b,c,a[f+3],16,-722521979);c=this.hh(c,d,e,b,a[f+6],23,76029189);b=this.hh(b,c,d,e,a[f+9],4,-640364487);e=this.hh(e,b,c,d,a[f+12],11,-421815835);d=this.hh(d,e,b,c,a[f+15],16,530742520);c=this.hh(c,d,e,b,a[f+2],23,-995338651);b=this.ii(b,c,d,e,a[f],6,-198630844);e=this.ii(e,b,c,d,a[f+7],10,1126891415);d=this.ii(d,
e,b,c,a[f+14],15,-1416354905);c=this.ii(c,d,e,b,a[f+5],21,-57434055);b=this.ii(b,c,d,e,a[f+12],6,1700485571);e=this.ii(e,b,c,d,a[f+3],10,-1894986606);d=this.ii(d,e,b,c,a[f+10],15,-1051523);c=this.ii(c,d,e,b,a[f+1],21,-2054922799);b=this.ii(b,c,d,e,a[f+8],6,1873313359);e=this.ii(e,b,c,d,a[f+15],10,-30611744);d=this.ii(d,e,b,c,a[f+6],15,-1560198380);c=this.ii(c,d,e,b,a[f+13],21,1309151649);b=this.ii(b,c,d,e,a[f+4],6,-145523070);e=this.ii(e,b,c,d,a[f+11],10,-1120210379);d=this.ii(d,e,b,c,a[f+2],15,718787259);
c=this.ii(c,d,e,b,a[f+9],21,-343485551);b=this.addme(b,g);c=this.addme(c,h);d=this.addme(d,k);e=this.addme(e,l);f+=16}return[b,c,d,e]}};var A=function(a){this.length=a.byteLength;this.b=new Uint8Array(a);this.b.bufferValue=a;a.hxBytes=this;a.bytes=this.b};A.__name__=!0;A.alloc=function(a){return new A(new ArrayBuffer(a))};A.ofString=function(a,b){b=[];for(var c=0;c<a.length;){var d=a.charCodeAt(c++);55296<=d&&56319>=d&&(d=d-55232<<10|a.charCodeAt(c++)&1023);127>=d?b.push(d):(2047>=d?b.push(192|d>>
6):(65535>=d?b.push(224|d>>12):(b.push(240|d>>18),b.push(128|d>>12&63)),b.push(128|d>>6&63)),b.push(128|d&63))}return new A((new Uint8Array(b)).buffer)};A.ofData=function(a){var b=a.hxBytes;return null!=b?b:new A(a)};A.ofHex=function(a){if(0!=(a.length&1))throw v.thrown("Not a hex string (odd number of digits)");for(var b=[],c=0,d=a.length>>1;c<d;){var e=a.charCodeAt(2*c),f=a.charCodeAt(2*c+1);e=(e&15)+9*((e&64)>>6);f=(f&15)+9*((f&64)>>6);b.push((e<<4|f)&255);++c}return new A((new Uint8Array(b)).buffer)};
A.fastGet=function(a,b){return a.bytes[b]};A.prototype={get:function(a){return this.b[a]},set:function(a,b){this.b[a]=b&255},blit:function(a,b,c,d){if(0>a||0>c||0>d||a+d>this.length||c+d>b.length)throw v.thrown(L.OutsideBounds);0==c&&d==b.b.byteLength?this.b.set(b.b,a):this.b.set(b.b.subarray(c,c+d),a)},fill:function(a,b,c){for(var d=0;d<b;)d++,this.b[a++]=c&255},sub:function(a,b){if(0>a||0>b||a+b>this.length)throw v.thrown(L.OutsideBounds);return new A(this.b.buffer.slice(a+this.b.byteOffset,a+this.b.byteOffset+
b))},compare:function(a){for(var b=this.b,c=a.b,d=0,e=this.length<a.length?this.length:a.length;d<e;){var f=d++;if(b[f]!=c[f])return b[f]-c[f]}return this.length-a.length},initData:function(){null==this.data&&(this.data=new DataView(this.b.buffer,this.b.byteOffset,this.b.byteLength))},getDouble:function(a){null==this.data&&(this.data=new DataView(this.b.buffer,this.b.byteOffset,this.b.byteLength));return this.data.getFloat64(a,!0)},getFloat:function(a){null==this.data&&(this.data=new DataView(this.b.buffer,
this.b.byteOffset,this.b.byteLength));return this.data.getFloat32(a,!0)},setDouble:function(a,b){null==this.data&&(this.data=new DataView(this.b.buffer,this.b.byteOffset,this.b.byteLength));this.data.setFloat64(a,b,!0)},setFloat:function(a,b){null==this.data&&(this.data=new DataView(this.b.buffer,this.b.byteOffset,this.b.byteLength));this.data.setFloat32(a,b,!0)},getUInt16:function(a){null==this.data&&(this.data=new DataView(this.b.buffer,this.b.byteOffset,this.b.byteLength));return this.data.getUint16(a,
!0)},setUInt16:function(a,b){null==this.data&&(this.data=new DataView(this.b.buffer,this.b.byteOffset,this.b.byteLength));this.data.setUint16(a,b,!0)},getInt32:function(a){null==this.data&&(this.data=new DataView(this.b.buffer,this.b.byteOffset,this.b.byteLength));return this.data.getInt32(a,!0)},setInt32:function(a,b){null==this.data&&(this.data=new DataView(this.b.buffer,this.b.byteOffset,this.b.byteLength));this.data.setInt32(a,b,!0)},getInt64:function(a){return new ha(this.getInt32(a+4),this.getInt32(a))},
setInt64:function(a,b){this.setInt32(a,b.low);this.setInt32(a+4,b.high)},getString:function(a,b,c){if(0>a||0>b||a+b>this.length)throw v.thrown(L.OutsideBounds);c="";var d=this.b,e=ba.fromCharCode,f=a;for(a+=b;f<a;)if(b=d[f++],128>b){if(0==b)break;c+=e(b)}else if(224>b)c+=e((b&63)<<6|d[f++]&127);else if(240>b){var g=d[f++];c+=e((b&31)<<12|(g&127)<<6|d[f++]&127)}else{g=d[f++];var h=d[f++];b=(b&15)<<18|(g&127)<<12|(h&127)<<6|d[f++]&127;c+=e((b>>10)+55232);c+=e(b&1023|56320)}return c},readString:function(a,
b){return this.getString(a,b)},toString:function(){return this.getString(0,this.length)},toHex:function(){for(var a,b="",c=[],d=0,e=16;d<e;)a=d++,c.push(t.cca("0123456789abcdef",a));d=0;for(e=this.length;d<e;)a=d++,a=this.b[a],b+=String.fromCodePoint(c[a>>4]),b+=String.fromCodePoint(c[a&15]);return b},getData:function(){return this.b.bufferValue}};h=R["haxe.io.Encoding"]={__ename__:!0,__constructs__:null,UTF8:{_hx_name:"UTF8",_hx_index:0,__enum__:"haxe.io.Encoding",toString:n},RawNative:{_hx_name:"RawNative",
_hx_index:1,__enum__:"haxe.io.Encoding",toString:n}};h.__constructs__=[h.UTF8,h.RawNative];var L=R["haxe.io.Error"]={__ename__:!0,__constructs__:null,Blocked:{_hx_name:"Blocked",_hx_index:0,__enum__:"haxe.io.Error",toString:n},Overflow:{_hx_name:"Overflow",_hx_index:1,__enum__:"haxe.io.Error",toString:n},OutsideBounds:{_hx_name:"OutsideBounds",_hx_index:2,__enum__:"haxe.io.Error",toString:n},Custom:(p=function(a){return{_hx_index:3,e:a,__enum__:"haxe.io.Error",toString:n}},p._hx_name="Custom",p.__params__=
["e"],p)};L.__constructs__=[L.Blocked,L.Overflow,L.OutsideBounds,L.Custom];var J=function(){};J.__name__=!0;J.join=function(a){for(var b=[],c=0;c<a.length;){var d=a[c];++c;null!=d&&""!=d&&b.push(d)}a=b;if(0==a.length)return"";d=a[0];b=1;for(c=a.length;b<c;){var e=b++;d=J.addTrailingSlash(d);d+=a[e]}return J.normalize(d)};J.normalize=function(a){a=a.split("\\").join("/");if("/"==a)return"/";for(var b=[],c=0,d=a.split("/");c<d.length;){var e=d[c];++c;".."==e&&0<b.length&&".."!=b[b.length-1]?b.pop():
""==e?(0<b.length||47==t.cca(a,0))&&b.push(e):"."!=e&&b.push(e)}a="";d=c=!1;e=0;for(b=b.join("/");e<b.length;){var f=b,g=e++,h=f.charCodeAt(g);55296<=h&&56319>=h&&(h=h-55232<<10|f.charCodeAt(g+1)&1023);f=h;65536<=f&&++e;switch(f){case 47:c?(c=!1,d&&(a+="/",d=!1),a+=String.fromCodePoint(f)):d=!0;break;case 58:a+=":";c=!0;break;default:c=!1,d&&(a+="/",d=!1),a+=String.fromCodePoint(f)}}return a};J.addTrailingSlash=function(a){if(0==a.length)return"/";var b=a.lastIndexOf("/"),c=a.lastIndexOf("\\");return b<
c?c!=a.length-1?a+"\\":a:b!=a.length-1?a+"/":a};p=function(){};p.__name__=!0;p.sliceImpl=function(a,b){a=new Uint8Array(this,a,null==b?null:b-a);b=new Uint8Array(a.byteLength);b.set(a);return b.buffer};var D=function(a){this.target=this.currentTarget=null;this.cancelBubble=this.cancelable=!1;this.type=a};D.__name__=!0;var X=function(){D.call(this,"devicemotion")};X.__name__=!0;X.__super__=D;X.prototype=m(D.prototype,{});var S=function(a){D.call(this,a);this.currentTarget=this.target=window.canvas};
S.__name__=!0;S.__super__=D;S.prototype=m(D.prototype,{});var T=function(a){this.changedTouches=[];this.targetTouches=[];this.touches=[];D.call(this,a);this.currentTarget=this.target=window.canvas};T.__name__=!0;T.__super__=D;T.prototype=m(D.prototype,{preventDefault:function(){}});w.$haxeUID|=0;"undefined"!=typeof performance&&"function"==typeof performance.now&&(t.now=performance.now.bind(performance));null==String.fromCodePoint&&(String.fromCodePoint=function(a){return 65536>a?String.fromCharCode(a):
String.fromCharCode((a>>10)+55232)+String.fromCharCode((a&1023)+56320)});String.__name__=!0;Array.__name__=!0;Date.__name__="Date";H.__toStr={}.toString;null==ArrayBuffer.prototype.slice&&(ArrayBuffer.prototype.slice=p.sliceImpl);E.CANVAS_COUNT=0;B.CONTEXT2D_COUNT=0;B.__measureTextSizeMaps=new O;z.IMAGE_COUNT=0;k.START="wxfile://";k.cacheExt=["png","json","mp3","xml","jpg"];k._isCanCache=!0;k.tempFileMaps=new O;x.CONNECTING=0;x.OPEN=1;x.CLOSING=2;x.CLOSED=3;g.canvas=new E;g.startTouch=[];y.UNSEND=
0;y.OPENED=1;y.HEADERS_RECEIVED=2;y.LOADING=3;y.DONE=4;g.main()})("undefined"!=typeof exports?exports:"undefined"!=typeof window?window:"undefined"!=typeof self?self:this,"undefined"!=typeof window?window:"undefined"!=typeof global?global:"undefined"!=typeof self?self:this);
